module AbnAmro
  class Internetkassa
    class Response
      module Codes
        STATUS_CODES = {
          "0"  => "Incomplete or invalid",
          "1"  => "Cancelled by client",
          "2"  => "Authorization refused",
          "4"  => "Order stored",
          "41" => "Waiting client payment",
          "5"  => "Authorized",
          "51" => "Authorization waiting",
          "52" => "Authorization not known",
          "55" => "Stand-by",
          "59" => "Authoriz. to get manually",
          "6"  => "Authorized and cancelled",
          "61" => "Author. deletion waiting",
          "62" => "Author. deletion uncertain",
          "63" => "Author. deletion refused",
          "64" => "Authorized and cancelled",
          "7"  => "Payment deleted",
          "71" => "Payment deletion pending",
          "72" => "Payment deletion uncertain",
          "73" => "Payment deletion refused",
          "74" => "Payment deleted",
          "75" => "Deletion processed by merchant",
          "8"  => "Refund",
          "81" => "Refund pending",
          "82" => "Refund uncertain",
          "83" => "Refund refused",
          "84" => "Payment declined by the acquirer",
          "85" => "Refund processed by merchant",
          "9"  => "Payment requested",
          "91" => "Payment processing",
          "92" => "Payment uncertain",
          "93" => "Payment refused",
          "94" => "Refund declined by the acquirer",
          "95" => "Payment processed by merchant",
          "99" => "Being processed",
        }
        
        ERROR_CODES = {
          "0020001002" => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "0020001003" => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "0020001004" => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "0020001005" => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "0020001006" => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "0020001007" => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "0020001008" => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "0020001009" => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "0020001010" => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "0030001999" => { :retry => false, :explanation => "Our payment system is currently under maintenance, please try later" },
          "0050001005" => { :retry => false, :explanation => "Expiry date error" },
          "0050001007" => { :retry => false, :explanation => "Requested Operation code not allowed" },
          "0050001008" => { :retry => false, :explanation => "Invalid delay value" },
          "0050001010" => { :retry => false, :explanation => "Input date in invalid format" },
          "0050001013" => { :retry => false, :explanation => "Unable to parse socket input stream" },
          "0050001014" => { :retry => false, :explanation => "Error in parsing stream content" },
          "0050001015" => { :retry => false, :explanation => "Currency error" },
          "0050001016" => { :retry => false, :explanation => "Transaction still posted at end of wait" },
          "0050001017" => { :retry => false, :explanation => "Sync value not compatible with delay value" },
          "0050001019" => { :retry => false, :explanation => "Transaction duplicate of a pre-existing transaction" },
          "0050001020" => { :retry => false, :explanation => "Acceptation code empty while required for the transaction" },
          "0050001024" => { :retry => false, :explanation => "Maintenance acquirer differs from original transaction acquirer" },
          "0050001025" => { :retry => false, :explanation => "Maintenance merchant differs from original transaction merchant" },
          "0050001028" => { :retry => false, :explanation => "Maintenance operation not accurate for the original transaction" },
          "0050001031" => { :retry => false, :explanation => "Host application unknown for the transaction" },
          "0050001032" => { :retry => false, :explanation => "Unable to perform requested operation with requested currency" },
          "0050001033" => { :retry => false, :explanation => "Maintenance card number differs from original transaction card number" },
          "0050001034" => { :retry => false, :explanation => "Operation code not allowed" },
          "0050001035" => { :retry => false, :explanation => "Exception occurred in socket input stream treatment" },
          "0050001036" => { :retry => false, :explanation => "Card length does not correspond to an acceptable value for the brand" },
          "0050001068" => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "0050001069" => { :retry => false, :explanation => "Invalid check for CardID and Brand" },
          "0050001070" => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "0050001116" => { :retry => false, :explanation => "Unknown origin IP" },
          "0050001117" => { :retry => false, :explanation => "No origin IP detected" },
          "0050001118" => { :retry => false, :explanation => "Merchant configuration problem, please contact support" },
          "020001001"  => { :retry => true,  :explanation => "Authorization failed, please retry" },
          "10001001"   => { :retry => false, :explanation => "Communication failure" },
          "10001002"   => { :retry => false, :explanation => "Communication failure" },
          "10001003"   => { :retry => false, :explanation => "Communication failure" },
          "10001004"   => { :retry => false, :explanation => "Communication failure" },
          "10001005"   => { :retry => false, :explanation => "Communication failure" },
          "20001001"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001002"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001003"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001004"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001005"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001006"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001007"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001008"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001009"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001010"   => { :retry => false, :explanation => "We received an unknown status for the transaction. We will contact your acquirer and update the status of the transaction within one working day. Please check the status later." },
          "20001101"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "20001111"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "20002001"   => { :retry => false, :explanation => "Origin for the response of the bank can not be checked" },
          "20002002"   => { :retry => false, :explanation => "Beneficiary account number has been modified during processing" },
          "20002003"   => { :retry => false, :explanation => "Amount has been modified during processing" },
          "20002004"   => { :retry => false, :explanation => "Currency has been modified during processing" },
          "20002005"   => { :retry => false, :explanation => "No feedback from the bank server has been detected" },
          "30001001"   => { :retry => false, :explanation => "Payment refused by the acquirer" },
          "30001002"   => { :retry => false, :explanation => "Duplicate request" },
          "30001010"   => { :retry => true,  :explanation => "A technical problem occurred, please contact helpdesk" },
          "30001011"   => { :retry => true,  :explanation => "A technical problem occurred, please contact helpdesk" },
          "30001012"   => { :retry => false, :explanation => "Card black listed - Contact acquirer" },
          "30001051"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "30001054"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "30001057"   => { :retry => true,  :explanation => "Your merchant's acquirer is temporarily unavailable, please try later or choose another payment method." },
          "30001058"   => { :retry => true,  :explanation => "Your merchant's acquirer is temporarily unavailable, please try later or choose another payment method." },
          "30001090"   => { :retry => false, :explanation => "CVC check required by front end and returned invalid by acquirer" },
          "30001091"   => { :retry => false, :explanation => "ZIP check required by front end and returned invalid by acquirer" },
          "30001092"   => { :retry => false, :explanation => "Address check required by front end and returned as invalid by acquirer." },
          "30001100"   => { :retry => false, :explanation => "Unauthorized buyer's country" },
          "30001101"   => { :retry => false, :explanation => "IP country <> card country" },
          "30001102"   => { :retry => false, :explanation => "Number of different countries too high" },
          "30001110"   => { :retry => false, :explanation => "If the problem persists, please contact Support, or go to paysafecard's card balance page (https://customer.cc.at.paysafecard.com/psccustomer/GetWelcomePanelServlet?language=en) to see when the amount reserved on your card will be available again." },
          "30001120"   => { :retry => false, :explanation => "IP address in merchant's black list" },
          "30001130"   => { :retry => false, :explanation => "BIN in merchant's black list" },
          "30001140"   => { :retry => false, :explanation => "Card in merchant's card blacklist" },
          "30001141"   => { :retry => false, :explanation => "Email in blacklist" },
          "30001142"   => { :retry => false, :explanation => "Passenger name in blacklist" },
          "30001143"   => { :retry => false, :explanation => "Card holder name in blacklist" },
          "30001144"   => { :retry => false, :explanation => "Passenger name different from owner name" },
          "30001145"   => { :retry => false, :explanation => "Time to departure too short" },
          "30001150"   => { :retry => false, :explanation => "Card not configured in the system for this customer (CSL)" },
          "30001151"   => { :retry => false, :explanation => "REF1 not allowed for this relationship (Contract number" },
          "30001152"   => { :retry => false, :explanation => "Card/Supplier Amount limit reached (CSL)" },
          "30001153"   => { :retry => false, :explanation => "Card not allowed for this supplier (Date out of contract bounds)" },
          "30001154"   => { :retry => false, :explanation => "You have reached the usage limit allowed" },
          "30001155"   => { :retry => false, :explanation => "You have reached the usage limit allowed" },
          "30001156"   => { :retry => false, :explanation => "You have reached the usage limit allowed" },
          "30001157"   => { :retry => false, :explanation => "Unauthorized IP country for itinerary" },
          "30001158"   => { :retry => false, :explanation => "email usage limit reached" },
          "30001159"   => { :retry => false, :explanation => "Unauthorized card country/IP country combination" },
          "30001160"   => { :retry => false, :explanation => "Postcode in highrisk group" },
          "30001161"   => { :retry => false, :explanation => "generic blacklist match" },
          "30001180"   => { :retry => false, :explanation => "maximum scoring reached" },
          "30001997"   => { :retry => false, :explanation => "Authorization canceled by simulation" },
          "30001998"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "30001999"   => { :retry => true,  :explanation => "Your merchant's acquirer is temporarily unavailable, please try later or choose another payment method." },
          "30002001"   => { :retry => false, :explanation => "Payment refused by the financial institution" },
          "30021001"   => { :retry => false, :explanation => "Call acquirer support call number." },
          "30031001"   => { :retry => false, :explanation => "Invalid merchant number." },
          "30041001"   => { :retry => false, :explanation => "Retain card." },
          "30051001"   => { :retry => false, :explanation => "Authorization declined" },
          "30071001"   => { :retry => false, :explanation => "Retain card - special conditions." },
          "30121001"   => { :retry => false, :explanation => "Invalid transaction" },
          "30131001"   => { :retry => false, :explanation => "Invalid amount" },
          "30131002"   => { :retry => false, :explanation => "You have reached the total amount allowed" },
          "30141001"   => { :retry => false, :explanation => "Invalid card number" },
          "30151001"   => { :retry => false, :explanation => "Unknown acquiring institution." },
          "30171001"   => { :retry => false, :explanation => "Payment method cancelled by the buyer" },
          "30171002"   => { :retry => false, :explanation => "The maximum time allowed is elapsed." },
          "30191001"   => { :retry => false, :explanation => "Try again later." },
          "30201001"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "30301001"   => { :retry => false, :explanation => "Invalid format" },
          "30311001"   => { :retry => false, :explanation => "Unknown acquirer ID." },
          "30331001"   => { :retry => false, :explanation => "Card expired." },
          "30341001"   => { :retry => false, :explanation => "Suspicion of fraud." },
          "30381001"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "30401001"   => { :retry => false, :explanation => "Invalid functionM." },
          "30411001"   => { :retry => false, :explanation => "Lost card." },
          "30431001"   => { :retry => false, :explanation => "Stolen card, pick up" },
          "30511001"   => { :retry => false, :explanation => "Insufficient funds." },
          "30541001"   => { :retry => false, :explanation => "Card expired." },
          "30551001"   => { :retry => false, :explanation => "Invalid PIN." },
          "30561001"   => { :retry => false, :explanation => "Card not in authorizer's database." },
          "30571001"   => { :retry => false, :explanation => "Transaction not permitted on card." },
          "30581001"   => { :retry => false, :explanation => "Transaction interdite au terminal" },
          "30591001"   => { :retry => false, :explanation => "Suspicion of fraud." },
          "30601001"   => { :retry => false, :explanation => "The merchant must contact the acquirer." },
          "30611001"   => { :retry => true,  :explanation => "Amount exceeds card ceiling." },
          "30621001"   => { :retry => false, :explanation => "Restricted card." },
          "30631001"   => { :retry => false, :explanation => "Security policy not respected." },
          "30641001"   => { :retry => false, :explanation => "Amount changed from ref. trn." },
          "30681001"   => { :retry => false, :explanation => "Tardy response." },
          "30751001"   => { :retry => false, :explanation => "PIN entered incorrectly too often" },
          "30761001"   => { :retry => false, :explanation => "Card holder already contesting." },
          "30771001"   => { :retry => false, :explanation => "PIN entry required." },
          "30811001"   => { :retry => false, :explanation => "Message flow error." },
          "30821001"   => { :retry => false, :explanation => "Authorization center unavailable" },
          "30831001"   => { :retry => false, :explanation => "Authorization center unavailable" },
          "30901001"   => { :retry => false, :explanation => "Temporary system shutdown." },
          "30911001"   => { :retry => false, :explanation => "Acquirer unavailable." },
          "30921001"   => { :retry => false, :explanation => "Invalid card type for acquirer." },
          "30941001"   => { :retry => false, :explanation => "Duplicate transaction" },
          "30961001"   => { :retry => true,  :explanation => "Processing temporarily not possible" },
          "30971001"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "30981001"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "31011001"   => { :retry => false, :explanation => "Unknown acceptance code" },
          "31021001"   => { :retry => false, :explanation => "Invalid currency" },
          "31031001"   => { :retry => false, :explanation => "Acceptance code missing" },
          "31041001"   => { :retry => false, :explanation => "Inactive card" },
          "31051001"   => { :retry => false, :explanation => "Merchant not active" },
          "31061001"   => { :retry => false, :explanation => "Invalid expiration date" },
          "31071001"   => { :retry => false, :explanation => "Interrupted host communication" },
          "31081001"   => { :retry => false, :explanation => "Card refused" },
          "31091001"   => { :retry => false, :explanation => "Invalid password" },
          "31101001"   => { :retry => false, :explanation => "Plafond transaction (majoré du bonus) dépassé" },
          "31111001"   => { :retry => false, :explanation => "Plafond mensuel (majoré du bonus) dépassé" },
          "31121001"   => { :retry => false, :explanation => "Plafond centre de facturation dépassé" },
          "31131001"   => { :retry => false, :explanation => "Plafond entreprise dépassé" },
          "31141001"   => { :retry => false, :explanation => "Code MCC du fournisseur non autorisé pour la carte" },
          "31151001"   => { :retry => false, :explanation => "Numéro SIRET du fournisseur non autorisé pour la carte" },
          "31161001"   => { :retry => false, :explanation => "This is not a valid online banking account" },
          "32001004"   => { :retry => false, :explanation => "A technical problem occurred, please try again." },
          "39991001"   => { :retry => false, :explanation => "A technical problem occurred, please contact the helpdesk of your acquirer" },
          "40001001"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001002"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001003"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001004"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001005"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001006"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001007"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001008"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001009"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001010"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001011"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "40001012"   => { :retry => true,  :explanation => "Your merchant's acquirer is temporarily unavailable, please try later or choose another payment method." },
          "40001013"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "40001016"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "40001018"   => { :retry => true,  :explanation => "A technical problem occurred, please try again." },
          "40001019"   => { :retry => true,  :explanation => "Sorry, an error occurred during processing. Please retry the operation (use back button of the browser). If problem persists, contact your merchant's helpdesk." },
          "40001050"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "40001134"   => { :retry => true,  :explanation => "Authentication failed, please retry or cancel." },
          "40001135"   => { :retry => true,  :explanation => "Authentication temporary unavailable, please retry or cancel." },
          "40001136"   => { :retry => true,  :explanation => "Technical problem with your browser, please retry or cancel" },
          "40001137"   => { :retry => true,  :explanation => "Your bank access control server is temporary unavailable, please retry or cancel" },
          "40001998"   => { :retry => false, :explanation => "Temporary technical problem. Please retry a little bit later." },
          "50001001"   => { :retry => false, :explanation => "Unknown card type" },
          "50001002"   => { :retry => false, :explanation => "Card number format check failed for given card number." },
          "50001003"   => { :retry => false, :explanation => "Merchant data error" },
          "50001004"   => { :retry => false, :explanation => "Merchant identification missing" },
          "50001005"   => { :retry => false, :explanation => "Expiry date error" },
          "50001006"   => { :retry => false, :explanation => "Amount is not a number" },
          "50001007"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001008"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001009"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001010"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001011"   => { :retry => false, :explanation => "Brand not supported for that merchant" },
          "50001012"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001013"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001014"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001015"   => { :retry => false, :explanation => "Invalid currency code" },
          "50001016"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001017"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001018"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001019"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001020"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001021"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001022"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001023"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001024"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001025"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001026"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001027"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001028"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001029"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001030"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001031"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001032"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001033"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001034"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001035"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001036"   => { :retry => false, :explanation => "Card length does not correspond to an acceptable value for the brand" },
          "50001037"   => { :retry => false, :explanation => "Purchasing card number for a regular merchant" },
          "50001038"   => { :retry => false, :explanation => "Non Purchasing card for a Purchasing card merchant" },
          "50001039"   => { :retry => false, :explanation => "Details sent for a non-Purchasing card merchant, please contact helpdesk" },
          "50001040"   => { :retry => false, :explanation => "Details not sent for a Purchasing card transaction, please contact helpdesk" },
          "50001041"   => { :retry => false, :explanation => "Payment detail validation failed" },
          "50001042"   => { :retry => false, :explanation => "Given transactions amounts (tax,discount,shipping,net,etc…) do not compute correctly together" },
          "50001043"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001044"   => { :retry => false, :explanation => "No acquirer configured for this operation" },
          "50001045"   => { :retry => false, :explanation => "No UID configured for this operation" },
          "50001046"   => { :retry => false, :explanation => "Operation not allowed for the merchant" },
          "50001047"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001048"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001049"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001050"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001051"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001052"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001053"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001054"   => { :retry => false, :explanation => "Card detection routine did not find any brand that matches" },
          "50001055"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001056"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001057"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001058"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001059"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001060"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001061"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001062"   => { :retry => false, :explanation => "A technical problem occurred, please contact helpdesk" },
          "50001063"   => { :retry => false, :explanation => "Card Issue Number does not correspond to range or not present" },
          "50001064"   => { :retry => false, :explanation => "Start Date not valid or not present" },
          "50001066"   => { :retry => false, :explanation => "Format of CVC code invalid" },
          "50001067"   => { :retry => false, :explanation => "The merchant is not enrolled for 3D-Secure" },
          "50001068"   => { :retry => false, :explanation => "The card number or account number (PAN) is invalid" },
          "50001069"   => { :retry => false, :explanation => "Invalid check for CardID and Brand" },
          "50001070"   => { :retry => false, :explanation => "The ECI value given is either not supported, or in conflict with other data in the transaction" },
          "50001071"   => { :retry => false, :explanation => "Incomplete TRN demat" },
          "50001072"   => { :retry => false, :explanation => "Incomplete PAY demat" },
          "50001073"   => { :retry => false, :explanation => "No demat APP" },
          "50001074"   => { :retry => false, :explanation => "Authorisation too old" },
          "50001075"   => { :retry => false, :explanation => "VERRes was an error message" },
          "50001076"   => { :retry => false, :explanation => "DCP amount greater than autorisation amount" },
          "50001077"   => { :retry => false, :explanation => "Details negative amount" },
          "50001078"   => { :retry => false, :explanation => "Details negative quantity" },
          "50001079"   => { :retry => false, :explanation => "Could not decode/decompress received PARes (3D-Secure)" },
          "50001080"   => { :retry => false, :explanation => "Received PARes was an erereor message from ACS (3D-Secure)" },
          "50001081"   => { :retry => false, :explanation => "Received PARes format was invalid according to the 3DS specifications (3D-Secure)" },
          "50001082"   => { :retry => false, :explanation => "PAReq/PARes reconciliation failure (3D-Secure)" },
          "50001084"   => { :retry => false, :explanation => "Maximum amount reached" },
          "50001087"   => { :retry => false, :explanation => "The transaction type requires authentication, please check with your bank." },
          "50001090"   => { :retry => false, :explanation => "CVC missing at input, but CVC check asked" },
          "50001091"   => { :retry => false, :explanation => "ZIP missing at input, but ZIP check asked" },
          "50001092"   => { :retry => false, :explanation => "Address missing at input, but Address check asked" },
          "50001095"   => { :retry => false, :explanation => "Invalid date of birth" },
          "50001096"   => { :retry => false, :explanation => "Invalid commodity code" },
          "50001097"   => { :retry => false, :explanation => "The requested currency and brand are incompatible." },
          "50001111"   => { :retry => false, :explanation => "Data validation error" },
          "50001113"   => { :retry => false, :explanation => "This order has already been processed" },
          "50001114"   => { :retry => false, :explanation => "Error pre-payment check page access" },
          "50001115"   => { :retry => false, :explanation => "Request not received in secure mode" },
          "50001116"   => { :retry => false, :explanation => "Unknown IP address origin" },
          "50001117"   => { :retry => false, :explanation => "NO IP address origin" },
          "50001118"   => { :retry => false, :explanation => "Pspid not found or not correct" },
          "50001119"   => { :retry => false, :explanation => "Password incorrect or disabled due to numbers of errors" },
          "50001120"   => { :retry => false, :explanation => "Invalid currency" },
          "50001121"   => { :retry => false, :explanation => "Invalid number of decimals for the currency" },
          "50001122"   => { :retry => false, :explanation => "Currency not accepted by the merchant" },
          "50001123"   => { :retry => false, :explanation => "Card type not active" },
          "50001124"   => { :retry => false, :explanation => "Number of lines don't match with number of payments" },
          "50001125"   => { :retry => false, :explanation => "Format validation error" },
          "50001126"   => { :retry => false, :explanation => "Overflow in data capture requests for the original order" },
          "50001127"   => { :retry => false, :explanation => "The original order is not in a correct status" },
          "50001128"   => { :retry => false, :explanation => "missing authorization code for unauthorized order" },
          "50001129"   => { :retry => false, :explanation => "Overflow in refunds requests" },
          "50001130"   => { :retry => false, :explanation => "Error access to original order" },
          "50001131"   => { :retry => false, :explanation => "Error access to original history item" },
          "50001132"   => { :retry => false, :explanation => "The Selected Catalog is empty" },
          "50001133"   => { :retry => false, :explanation => "Duplicate request" },
          "50001134"   => { :retry => false, :explanation => "Authentication failed, please retry or cancel." },
          "50001135"   => { :retry => false, :explanation => "Authentication temporary unavailable, please retry or cancel." },
          "50001136"   => { :retry => false, :explanation => "Technical problem with your browser, please retry or cancel" },
          "50001137"   => { :retry => false, :explanation => "Your bank access control server is temporary unavailable, please retry or cancel" },
          "50001150"   => { :retry => false, :explanation => "Fraud Detection, Technical error (IP not valid)" },
          "50001151"   => { :retry => false, :explanation => "Fraud detection : technical error (IPCTY unknown or error)" },
          "50001152"   => { :retry => false, :explanation => "Fraud detection : technical error (CCCTY unknown or error)" },
          "50001153"   => { :retry => false, :explanation => "Overflow in redo-authorisation requests" },
          "50001170"   => { :retry => false, :explanation => "Dynamic BIN check failed" },
          "50001171"   => { :retry => false, :explanation => "Dynamic country check failed" },
          "50001172"   => { :retry => false, :explanation => "Error in Amadeus signature" },
          "60000001"   => { :retry => false, :explanation => "account number unknown" },
          "60000003"   => { :retry => false, :explanation => "not credited dd-mm-yy" },
          "60000005"   => { :retry => false, :explanation => "name/number do not correspond" },
          "60000007"   => { :retry => false, :explanation => "account number blocked" },
          "60000008"   => { :retry => false, :explanation => "specific direct debit block" },
          "60000009"   => { :retry => false, :explanation => "account number WKA" },
          "60000010"   => { :retry => false, :explanation => "administrative reason" },
          "60000011"   => { :retry => false, :explanation => "account number expired" },
          "60000012"   => { :retry => false, :explanation => "no direct debit authorisation given" },
          "60000013"   => { :retry => false, :explanation => "debit not approved" },
          "60000014"   => { :retry => false, :explanation => "double payment" },
          "60000018"   => { :retry => false, :explanation => "name/address/city not entered" },
          "60001001"   => { :retry => false, :explanation => "no original direct debit for revocation" },
          "60001002"   => { :retry => false, :explanation => "payer’s account number format error" },
          "60001004"   => { :retry => false, :explanation => "payer’s account at different bank" },
          "60001005"   => { :retry => false, :explanation => "payee’s account at different bank" },
          "60001006"   => { :retry => false, :explanation => "payee’s account number format error" },
          "60001007"   => { :retry => false, :explanation => "payer’s account number blocked" },
          "60001008"   => { :retry => false, :explanation => "payer’s account number expired" },
          "60001009"   => { :retry => false, :explanation => "payee’s account number expired" },
          "60001010"   => { :retry => false, :explanation => "direct debit not possible" },
          "60001011"   => { :retry => false, :explanation => "creditor payment not possible" },
          "60001012"   => { :retry => false, :explanation => "payer’s account number unknown WKA-number" },
          "60001013"   => { :retry => false, :explanation => "payee’s account number unknown WKA-number" },
          "60001014"   => { :retry => false, :explanation => "impermissible WKA transaction" },
          "60001015"   => { :retry => false, :explanation => "period for revocation expired" },
          "60001017"   => { :retry => false, :explanation => "reason for revocation not correct" },
          "60001018"   => { :retry => false, :explanation => "original run number not numeric" },
          "60001019"   => { :retry => false, :explanation => "payment ID incorrect" },
          "60001020"   => { :retry => false, :explanation => "amount not numeric" },
          "60001021"   => { :retry => false, :explanation => "amount zero not permitted" },
          "60001022"   => { :retry => false, :explanation => "negative amount not permitted" },
          "60001023"   => { :retry => false, :explanation => "payer and payee giro account number" },
          "60001025"   => { :retry => false, :explanation => "processing code (verwerkingscode) incorrect" },
          "60001028"   => { :retry => false, :explanation => "revocation not permitted" },
          "60001029"   => { :retry => false, :explanation => "guaranteed direct debit on giro account number" },
          "60001030"   => { :retry => false, :explanation => "NBC transaction type incorrect" },
          "60001031"   => { :retry => false, :explanation => "description too large" },
          "60001032"   => { :retry => false, :explanation => "book account number not issued" },
          "60001034"   => { :retry => false, :explanation => "book account number incorrect" },
          "60001035"   => { :retry => false, :explanation => "payer’s account number not numeric" },
          "60001036"   => { :retry => false, :explanation => "payer’s account number not eleven-proof" },
          "60001037"   => { :retry => false, :explanation => "payer’s account number not issued" },
          "60001039"   => { :retry => false, :explanation => "payer’s account number of DNB/BGC/BLA" },
          "60001040"   => { :retry => false, :explanation => "payee’s account number not numeric" },
          "60001041"   => { :retry => false, :explanation => "payee’s account number not eleven-proof" },
          "60001042"   => { :retry => false, :explanation => "payee’s account number not issued" },
          "60001044"   => { :retry => false, :explanation => "payee’s account number unknown" },
          "60001050"   => { :retry => false, :explanation => "payee’s name missing" },
          "60001051"   => { :retry => false, :explanation => "indicate payee’s bank account number instead of 3102" },
          "60001052"   => { :retry => false, :explanation => "no direct debit contract" },
          "60001053"   => { :retry => false, :explanation => "amount beyond bounds" },
          "60001054"   => { :retry => false, :explanation => "selective direct debit block" },
          "60001055"   => { :retry => false, :explanation => "original run number unknown" },
          "60001057"   => { :retry => false, :explanation => "payer’s name missing" },
          "60001058"   => { :retry => false, :explanation => "payee’s account number missing" },
          "60001059"   => { :retry => false, :explanation => "restore not permitted" },
          "60001060"   => { :retry => false, :explanation => "bank’s reference (navraaggegeven) missing" },
          "60001061"   => { :retry => false, :explanation => "BEC/GBK number incorrect" },
          "60001062"   => { :retry => false, :explanation => "BEC/GBK code incorrect" },
          "60001087"   => { :retry => false, :explanation => "book account number not numeric" },
          "60001090"   => { :retry => false, :explanation => "cancelled on request" },
          "60001091"   => { :retry => false, :explanation => "cancellation order executed" },
          "60001092"   => { :retry => false, :explanation => "cancelled instead of bended" },
          "60001093"   => { :retry => false, :explanation => "book account number is a shortened account number" },
          "60001094"   => { :retry => false, :explanation => "instructing party account number not identical with payer" },
          "60001095"   => { :retry => false, :explanation => "payee unknown GBK acceptor" },
          "60001097"   => { :retry => false, :explanation => "instructing party account number not identical with payee" },
          "60001099"   => { :retry => false, :explanation => "clearing not permitted" },
          "60001101"   => { :retry => false, :explanation => "payer’s account number not spaces" },
          "60001102"   => { :retry => false, :explanation => "PAN length not numeric" },
          "60001103"   => { :retry => false, :explanation => "PAN length outside limits" },
          "60001104"   => { :retry => false, :explanation => "track number not numeric" },
          "60001105"   => { :retry => false, :explanation => "track number not valid" },
          "60001106"   => { :retry => false, :explanation => "PAN sequence number not numeric" },
          "60001107"   => { :retry => false, :explanation => "domestic PAN not numeric" },
          "60001108"   => { :retry => false, :explanation => "domestic PAN not eleven-proof" },
          "60001109"   => { :retry => false, :explanation => "domestic PAN not issued" },
          "60001110"   => { :retry => false, :explanation => "foreign PAN not numeric" },
          "60001111"   => { :retry => false, :explanation => "card valid date not numeric" },
          "60001112"   => { :retry => false, :explanation => "book period number (boekperiodenr) not numeric" },
          "60001113"   => { :retry => false, :explanation => "transaction number not numeric" },
          "60001114"   => { :retry => false, :explanation => "transaction time not numeric" },
          "60001115"   => { :retry => false, :explanation => "transaction no valid time" },
          "60001116"   => { :retry => false, :explanation => "transaction date not numeric" },
          "60001117"   => { :retry => false, :explanation => "transaction no valid date" },
          "60001118"   => { :retry => false, :explanation => "STAN not numeric" },
          "60001119"   => { :retry => false, :explanation => "instructing party’s name missing" },
          "60001120"   => { :retry => false, :explanation => "foreign amount (bedrag-vv) not numeric" },
          "60001122"   => { :retry => false, :explanation => "rate (verrekenkoers) not numeric" },
          "60001125"   => { :retry => false, :explanation => "number of decimals (aantaldecimalen) incorrect" },
          "60001126"   => { :retry => false, :explanation => "tariff (tarifering) not B/O/S" },
          "60001127"   => { :retry => false, :explanation => "domestic costs (kostenbinnenland) not numeric" },
          "60001128"   => { :retry => false, :explanation => "domestic costs (kostenbinnenland) not higher than zero" },
          "60001129"   => { :retry => false, :explanation => "foreign costs (kostenbuitenland) not numeric" },
          "60001130"   => { :retry => false, :explanation => "foreign costs (kostenbuitenland) not higher than zero" },
          "60001131"   => { :retry => false, :explanation => "domestic costs (kostenbinnenland) not zero" },
          "60001132"   => { :retry => false, :explanation => "foreign costs (kostenbuitenland) not zero" },
          "60001134"   => { :retry => false, :explanation => "Euro record not fully filled in" },
          "60001135"   => { :retry => false, :explanation => "Client currency incorrect" },
          "60001136"   => { :retry => false, :explanation => "Amount NLG not numeric" },
          "60001137"   => { :retry => false, :explanation => "Amount NLG not higher than zero" },
          "60001138"   => { :retry => false, :explanation => "Amount NLG not equal to Amount" },
          "60001139"   => { :retry => false, :explanation => "Amount NLG incorrectly converted" },
          "60001140"   => { :retry => false, :explanation => "Amount EUR not numeric" },
          "60001141"   => { :retry => false, :explanation => "Amount EUR not greater than zero" },
          "60001142"   => { :retry => false, :explanation => "Amount EUR not equal to Amount" },
          "60001143"   => { :retry => false, :explanation => "Amount EUR incorrectly converted" },
          "60001144"   => { :retry => false, :explanation => "Client currency not NLG" },
          "60001145"   => { :retry => false, :explanation => "rate euro-vv (Koerseuro-vv) not numeric" },
          "60001146"   => { :retry => false, :explanation => "comma rate euro-vv (Kommakoerseuro-vv) incorrect" },
          "60001147"   => { :retry => false, :explanation => "acceptgiro distributor not valid" },
          "60001148"   => { :retry => false, :explanation => "Original run number and/or BRN are missing" },
          "60001149"   => { :retry => false, :explanation => "Amount/Account number/ BRN different" },
          "60001150"   => { :retry => false, :explanation => "Direct debit already revoked/restored" },
          "60001151"   => { :retry => false, :explanation => "Direct debit already reversed/revoked/restored" },
          "60001153"   => { :retry => false, :explanation => "Payer’s account number not known" }
        }
      end
    end
  end
end